# Generated by Django 2.1.7 on 2019-04-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0002_auto_20190401_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(default='bearing', max_length=50),
        ),
    ]
